### ISSUE TITLE
Stuck at boot screen

### ISSUE THREAD

**Issue by Charliecoop** [SamarV-121/releases#4]
Previous builds worked however the latest version of LineageOS 18.1 as below doesn't load past the Samsung A40 powered by Android logo boot screen.

lineage-18.1-plus-20210709_122105-UNOFFICIAL-c8a2e8a-a40.zip

**Comment by SamarV-121** [comment]
You shouldn't flash builds which are not linked in SamarV-121.github.io

**Comment by Charliecoop** [comment]
ok, thanks for the heads up! I'll check that website instead. An XDA Developers forum post linked directly to this page rather than your webpage.

**Comment by SamarV-121** [comment]
https://t.me/lineage_7904

**Comment by SamarV-121** [comment]
Also PM me on tg if you are interested in testing more builds

https://t.me/SamarV121
